# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 23:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_marked', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='GameInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.GameSet')),
            ],
        ),
        migrations.AddField(
            model_name='gameinstance',
            name='game_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.GameSet'),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='game_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.GameInstance'),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='square_marked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.Square'),
        ),
    ]
