# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 21:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bingo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCard',
            fields=[
                ('game_card_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='gameinstance',
            name='id',
        ),
        migrations.AddField(
            model_name='gameinstance',
            name='game_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='gameinstance',
            name='player_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gameset',
            name='allow_free_space',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gameset',
            name='free_space',
            field=models.CharField(default='Free', max_length=1000),
        ),
        migrations.AddField(
            model_name='gameset',
            name='ordered_columns',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='square',
            name='column',
            field=models.CharField(choices=[('B', 'B'), ('I', 'I'), ('N', 'N'), ('G', 'G'), ('O', 'O')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='gamecard',
            name='game_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.GameInstance'),
        ),
        migrations.AddField(
            model_name='gamecard',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
