# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_auto_20171031_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecard',
            name='player_name',
            field=models.CharField(default='Player', max_length=64),
        ),
    ]
